# Generated by Django 6.0.4 on 2026-06-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('experience', models.TextField(help_text='Separate roles with new lines or use JSON')),
                ('education', models.TextField()),
                ('skills', models.CharField(help_text='Comma-separated skills', max_length=255)),
            ],
        ),
    ]
