# Generated by Django 6.0.4 on 2026-06-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_cvprofile_email_remove_cvprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
