# Generated by Django 6.0.4 on 2026-06-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cvprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='design_choice',
            field=models.CharField(choices=[('template1', 'Modern Green'), ('template2', 'Classic Slate'), ('template3', 'Creative Teal'), ('template4', 'Minimal Elegant'), ('template5', 'Executive Charcoal'), ('template6', 'Warm Ochre')], default='template1', max_length=20),
        ),
    ]
